title: Erin Oefelein # your name (or website title) here
logo: "/images/eo_headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data scientist with end-to-end expertise in building and deploying machine learning solutions — spanning churn modeling, demand forecasting, A/B testing, and recommendation systems — with a track record of delivering measurable business impact. Skilled in SQL, Python, SQL, Machine Learning and AI with strengths in full pipeline development, interpretability, and translating complex data into actionable insights that drive business strategy. 
  <br><br>
  Selected as both Graduate Assistant and Teaching Assistant for AI and Deep Learning courses based on academic excellence, and conducted research leading to a publication in ACS Materials on machine learning insights for water oxidation electrocatalysts. 
  <br><br>
  <a href="https://www.linkedin.com/in/erin-oefelein/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
